### ISSUE TITLE
add brackets are colored 

### ISSUE THREAD

**Issue by bad4iz** [sh7dm/bright-night#1]
add when brackets are colored depending on the nesting. very convenient to read the code and navigate

**Comment by dsseng** [comment]
it'll be nice to have this! I sometimes have these bracket issues, so I'll do that when I have time.

**Comment by dsseng** [comment]
I'm sorry but this cannot be achieved using VS Code theming capabilities, but this extension can help:
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
